# Generated by Django 4.2 on 2023-06-20 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='students_list',
            field=models.ManyToManyField(blank=True, related_name='teacher_students', to=settings.AUTH_USER_MODEL, verbose_name='Список студентов'),
        ),
    ]
