# Generated by Django 4.2.2 on 2023-07-07 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600, verbose_name='Вопрос')),
                ('task_body', models.JSONField(blank=True, null=True)),
                ('task_text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to='task_files', verbose_name='Загрузить файл')),
                ('url', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ссылка на ресурс')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_exercise', to='KaifSchool.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема урока')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='theme_img', verbose_name='Обложка')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_exercise', to='KaifSchool.exercise', verbose_name='Упражнение')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_homework', to='KaifSchool.exercise', verbose_name='Домашнее задание')),
                ('theme_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=600, null=True, verbose_name='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to='KaifSchool.task', verbose_name='Задача')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='KaifSchool.tasktype', verbose_name='Тип задания'),
        ),
        migrations.CreateModel(
            name='LessonCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оплаченные уроки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_balance', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оплаченные уроки',
                'verbose_name_plural': 'Оплаченные уроки',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробный урок')),
                ('status', models.CharField(choices=[('Planned', 'Запланирован'), ('Ongoing', 'Идет'), ('Completed', 'Прошёл'), ('Canceled', 'Отменён')], default='Planned', max_length=200, verbose_name='Статус')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Продолжительность')),
                ('lesson_date', models.DateTimeField(verbose_name='Дата и время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hash_lesson', models.CharField(blank=True, null=True, verbose_name='Hash meeting')),
                ('session_hash', models.CharField(blank=True, null=True, verbose_name='Session hash')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_theme', to='KaifSchool.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
